version: '3.8'
services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: fds_monitor
    restart: unless-stopped

  web:
    build:
      context: ./web-dashboard
      dockerfile: Dockerfile
    container_name: fds_web
    ports:
      - "3034:3034"
    environment:
      - PORT=3034
      - WEB_DASH_DEBUG=0
      - MONITOR_DB_PATH=/repo/kick_monitor.sqlite3
      - FDS_DB_PATH=/repo/fds_bot.db
    volumes:
      - ./web-dashboard:/app
      - ./:/repo  # mount repo at /repo so sqlite files are accessible
    depends_on:
      - monitor
    restart: unless-stopped
